prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
theme:
  colors:
    text:
      primary: "#F7F1FF"
      secondary: "#5AD4E6"
      inverted: "#F7F1FF"
      faint: "#3E4057"
      warning: "#FC618D"
      success: "#7BD88F"
    background:
      selected: "#535155"
    border:
      primary: "#948AE3"
      secondary: "#7BD88F"
      faint: "#3E4057"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
